import {
  Leaf,
  Droplets,
  Zap,
  Box,
  Heart,
  Lightbulb
} from 'lucide-react';
export const CATEGORIES = [
  {
    id: "sd",
    name: "Sustainable Design",
    shortName: "Site Design",
    icon: <Leaf className="w-5 h-5" />,
    totalPoints: 20,
    credits: [
      {
        id: "sd-m1",
        name: "Local Building Regulations",
        points: 0,
        mandatory: true,
      },
      { id: "sd-m2", name: "Soil Erosion Control", points: 0, mandatory: true },
      { id: "sd-1", name: "Natural Topography & Vegetation", points: 4 },
      { id: "sd-2", name: "Heat Island Effect, Roof & Non-roof", points: 4 },
      { id: "sd-3", name: "Passive Architecture", points: 2 },
      { id: "sd-4", name: "Universal Design", points: 2 },
      { id: "sd-5", name: "Green Parking Facility", points: 4 },
      { id: "sd-6", name: "Access to Amenities", points: 2 },
      {
        id: "sd-7",
        name: "Basic Facilities for Construction Workforce",
        points: 1,
      },
      { id: "sd-8", name: "Green Education & Awareness", points: 1 },
    ],
  },
  {
    id: "wc",
    name: "Water Conservation",
    shortName: "Water",
    icon: <Droplets className="w-5 h-5" />,
    totalPoints: 23,
    credits: [
      {
        id: "wc-m1",
        name: "Water Efficient Plumbing Fixtures",
        points: 0,
        mandatory: true,
      },
      { id: "wc-m2", name: "Rainwater Harvesting", points: 0, mandatory: true },
      { id: "wc-1", name: "Water Efficient Plumbing Fixtures", points: 6 },
      { id: "wc-2", name: "Landscape Design", points: 3 },
      { id: "wc-3", name: "Management of Irrigation System", points: 2 },
      { id: "wc-4", name: "Recycle & Reuse of Waste water", points: 4 },
      { id: "wc-5", name: "Water Quality", points: 1 },
      { id: "wc-6", name: "Enhanced Rainwater Harvesting", points: 4 },
      { id: "wc-7", name: "Water Metering", points: 3 },
    ],
  },
  {
    id: "ee",
    name: "Energy Efficiency",
    shortName: "Energy",
    icon: <Zap className="w-5 h-5" />,
    totalPoints: 20,
    credits: [
      { id: "ee-m1", name: "HCFC Free Equipment", points: 0, mandatory: true },
      {
        id: "ee-m2",
        name: "Minimum Energy Performance",
        points: 0,
        mandatory: true,
      },
      { id: "ee-1", name: "Enhanced Energy Performance", points: 10 },
      { id: "ee-2", name: "Alternate Water Heating system", points: 3 },
      { id: "ee-3", name: "On-site Renewable Energy", points: 4 },
      {
        id: "ee-4",
        name: "Energy efficiency in common area equipment",
        points: 1,
      },
      { id: "ee-5", name: "Integrated Energy Monitoring System", points: 2 },
    ],
  },
  {
    id: "mr",
    name: "Materials & Resources",
    shortName: "Materials",
    icon: <Box className="w-5 h-5" />,
    totalPoints: 18,
    credits: [
      {
        id: "mr-m1",
        name: "Separation of House-hold Waste",
        points: 0,
        mandatory: true,
      },
      { id: "mr-1", name: "Green Procurement Policy", points: 1 },
      { id: "mr-2", name: "Optimisation on Structural Design", points: 1 },
      { id: "mr-3", name: "Certified Green Products", points: 5 },
      { id: "mr-4", name: "Local Materials", points: 2 },
      { id: "mr-5", name: "Eco friendly wood based materials", points: 2 },
      { id: "mr-6", name: "Alternative Construction Material", points: 2 },
      {
        id: "mr-7",
        name: "Handling of Construction & Demolition Waste",
        points: 2,
      },
      { id: "mr-8", name: "Organic Waste treatment Post Occupancy", points: 3 },
    ],
  },
  {
    id: "rhw",
    name: "Resident Health & Wellbeing",
    shortName: "Health",
    icon: <Heart className="w-5 h-5" />,
    totalPoints: 14,
    credits: [
      { id: "rhw-m1", name: "Minimum Daylighting", points: 0, mandatory: true },
      { id: "rhw-m2", name: "Ventilation Design", points: 0, mandatory: true },
      { id: "rhw-m3", name: "No Smoking Policy", points: 0, mandatory: true },
      { id: "rhw-1", name: "Enhanced Daylighting", points: 2 },
      { id: "rhw-2", name: "Enhanced Ventilation Design", points: 2 },
      { id: "rhw-3", name: "Cross Ventilation", points: 4 },
      { id: "rhw-4", name: "Connectivity to Exteriors", points: 2 },
      { id: "rhw-5", name: "Low VOC Materials, Paints & Adhesives", points: 2 },
      { id: "rhw-6", name: "Facility for Physical Wellbeing", points: 2 },
    ],
  },
  {
    id: "id",
    name: "Innovation & Design",
    shortName: "Innovation",
    icon: <Lightbulb className="w-5 h-5" />,
    totalPoints: 5,
    credits: [
      { id: "id-1", name: "Innovation", points: 2 },
      { id: "id-2", name: "Exemplary Performance", points: 2 },
      { id: "id-3", name: "IGBC Accredited Professional", points: 1 },
    ],
  },
];
